apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: udagram-reverseproxy
  name: udagram-reverseproxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: udagram-reverseproxy
    spec:
      containers:
      - image: sabribouchlema/udagram-reverseproxy
        name: udagram-reverseproxy
        imagePullPolicy: Always             
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-reverseproxy
  name: udagram-reverseproxy-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: udagram-reverseproxy